# Generated by Django 4.1.3 on 2022-11-22 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=100)),
                ('id_type', models.CharField(max_length=25)),
                ('id_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('issued_do_ill', models.DateField()),
                ('issued_do_hos', models.DateField()),
                ('doc_name', models.CharField(max_length=50)),
                ('diagnosis', models.TextField()),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='UserCredential',
            fields=[
                ('id_user', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('fname', models.CharField(default=None, max_length=100)),
                ('user_email', models.CharField(default=None, max_length=100)),
                ('password', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'UserCredentials',
            },
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id_bill', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('payment_option', models.CharField(max_length=20)),
                ('total_charge', models.FloatField()),
                ('amt_paid', models.FloatField()),
                ('bal_due', models.FloatField()),
                ('billing_pro_info', models.CharField(max_length=100)),
                ('ins_group_no', models.IntegerField()),
                ('ins_fname', models.CharField(max_length=200)),
                ('ins_gender', models.CharField(max_length=7)),
                ('ins_address', models.CharField(max_length=100)),
                ('ins_mobile', models.BigIntegerField()),
                ('ins_plan_prog', models.CharField(max_length=100)),
                ('id_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
            options={
                'db_table': 'Billing',
            },
        ),
    ]
