# Generated by Django 4.1.3 on 2022-12-04 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_billing_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='id_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
